### ISSUE TITLE
Enhance command output

### ISSUE THREAD

**Issue by Hacksore** [ridvanaltun/dropbox-ignore-anywhere#7]
@ridvanaltun Really cool project here.

As of now it just dumps stdout/stderror object from the shell command. Would it not make more sense to only show stderr if something went wrong and showing a nicer success message.

So I'm suggesting
`di ignore node_modules` to output something like:
```
Successfully added the ignore attribute to "node_modules"
```

I can make a PR for this but just wanted to start the discussion first to make sure this change would be acceptable.

**Comment by ridvanaltun** [comment]
> @ridvanaltun Really cool project here.
> 
> As of now it just dumps stdout/stderror object from the shell command. Would it not make more sense to only show stderr if something went wrong and showing a nicer success message.
> 
> So I'm suggesting
> `di ignore node_modules` to output something like:
> 
> ```
> Successfully added the ignore attribute to "node_modules"
> ```
> 
> I can make a PR for this but just wanted to start the discussion first to make sure this change would be acceptable.

Thanks, it is a good idea.
